GENDER_MALE: str = "male"
GENDER_FEMALE: str = "female"
INIT_MONEY: int = 10000
INIT_SATIETY: int = 50
INIT_AGE: int = 20
INIT_DAYS_PASSED: int = 0
DAILY_LOOP_SLEEP_DURATION: int = 4
DAILY_LOOP_SLEEP_DURATION_DEBUG: int = 1
FILE_PATH_METADATA = "database/metadata.json"
FILE_PATH_RESIDENTS = "database/residents.json"
FILE_PATH_NAME_CANDIDATE = "database/name_candidate.json"
DEFAULT_DEBUG_MODE = False
INIT_PEOPLE_NUM: int = 2
